/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UneteAlEquipoRouteImport } from './routes/unete-al-equipo'
import { Route as TesorosAyacuchoRouteImport } from './routes/tesoros-ayacucho'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as RestauranteRouteImport } from './routes/restaurante'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as LibroDeReclamacionesRouteImport } from './routes/libro-de-reclamaciones'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FamiliaLasFloresRouteImport } from './routes/familia-las-flores'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CartaRouteImport } from './routes/carta'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RastreoOrderIdRouteImport } from './routes/rastreo/$orderId'
import { Route as DOrderIdRouteImport } from './routes/d/$orderId'

const UneteAlEquipoRoute = UneteAlEquipoRouteImport.update({
  id: '/unete-al-equipo',
  path: '/unete-al-equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const TesorosAyacuchoRoute = TesorosAyacuchoRouteImport.update({
  id: '/tesoros-ayacucho',
  path: '/tesoros-ayacucho',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteRoute = RestauranteRouteImport.update({
  id: '/restaurante',
  path: '/restaurante',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroDeReclamacionesRoute = LibroDeReclamacionesRouteImport.update({
  id: '/libro-de-reclamaciones',
  path: '/libro-de-reclamaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaLasFloresRoute = FamiliaLasFloresRouteImport.update({
  id: '/familia-las-flores',
  path: '/familia-las-flores',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaRoute = CartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreoOrderIdRoute = RastreoOrderIdRouteImport.update({
  id: '/rastreo/$orderId',
  path: '/rastreo/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DOrderIdRoute = DOrderIdRouteImport.update({
  id: '/d/$orderId',
  path: '/d/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caja': typeof CajaRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/familia-las-flores': typeof FamiliaLasFloresRoute
  '/galeria': typeof GaleriaRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/reservas': typeof ReservasRoute
  '/restaurante': typeof RestauranteRoute
  '/staff-login': typeof StaffLoginRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tesoros-ayacucho': typeof TesorosAyacuchoRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/d/$orderId': typeof DOrderIdRoute
  '/rastreo/$orderId': typeof RastreoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caja': typeof CajaRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/familia-las-flores': typeof FamiliaLasFloresRoute
  '/galeria': typeof GaleriaRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/reservas': typeof ReservasRoute
  '/restaurante': typeof RestauranteRoute
  '/staff-login': typeof StaffLoginRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tesoros-ayacucho': typeof TesorosAyacuchoRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/d/$orderId': typeof DOrderIdRoute
  '/rastreo/$orderId': typeof RastreoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caja': typeof CajaRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/familia-las-flores': typeof FamiliaLasFloresRoute
  '/galeria': typeof GaleriaRoute
  '/libro-de-reclamaciones': typeof LibroDeReclamacionesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/reservas': typeof ReservasRoute
  '/restaurante': typeof RestauranteRoute
  '/staff-login': typeof StaffLoginRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tesoros-ayacucho': typeof TesorosAyacuchoRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/d/$orderId': typeof DOrderIdRoute
  '/rastreo/$orderId': typeof RastreoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/caja'
    | '/carta'
    | '/contacto'
    | '/eventos'
    | '/familia-las-flores'
    | '/galeria'
    | '/libro-de-reclamaciones'
    | '/politica-de-privacidad'
    | '/reservas'
    | '/restaurante'
    | '/staff-login'
    | '/terminos-y-condiciones'
    | '/tesoros-ayacucho'
    | '/unete-al-equipo'
    | '/d/$orderId'
    | '/rastreo/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/caja'
    | '/carta'
    | '/contacto'
    | '/eventos'
    | '/familia-las-flores'
    | '/galeria'
    | '/libro-de-reclamaciones'
    | '/politica-de-privacidad'
    | '/reservas'
    | '/restaurante'
    | '/staff-login'
    | '/terminos-y-condiciones'
    | '/tesoros-ayacucho'
    | '/unete-al-equipo'
    | '/d/$orderId'
    | '/rastreo/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/caja'
    | '/carta'
    | '/contacto'
    | '/eventos'
    | '/familia-las-flores'
    | '/galeria'
    | '/libro-de-reclamaciones'
    | '/politica-de-privacidad'
    | '/reservas'
    | '/restaurante'
    | '/staff-login'
    | '/terminos-y-condiciones'
    | '/tesoros-ayacucho'
    | '/unete-al-equipo'
    | '/d/$orderId'
    | '/rastreo/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CajaRoute: typeof CajaRoute
  CartaRoute: typeof CartaRoute
  ContactoRoute: typeof ContactoRoute
  EventosRoute: typeof EventosRoute
  FamiliaLasFloresRoute: typeof FamiliaLasFloresRoute
  GaleriaRoute: typeof GaleriaRoute
  LibroDeReclamacionesRoute: typeof LibroDeReclamacionesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  ReservasRoute: typeof ReservasRoute
  RestauranteRoute: typeof RestauranteRoute
  StaffLoginRoute: typeof StaffLoginRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  TesorosAyacuchoRoute: typeof TesorosAyacuchoRoute
  UneteAlEquipoRoute: typeof UneteAlEquipoRoute
  DOrderIdRoute: typeof DOrderIdRoute
  RastreoOrderIdRoute: typeof RastreoOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unete-al-equipo': {
      id: '/unete-al-equipo'
      path: '/unete-al-equipo'
      fullPath: '/unete-al-equipo'
      preLoaderRoute: typeof UneteAlEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoros-ayacucho': {
      id: '/tesoros-ayacucho'
      path: '/tesoros-ayacucho'
      fullPath: '/tesoros-ayacucho'
      preLoaderRoute: typeof TesorosAyacuchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante': {
      id: '/restaurante'
      path: '/restaurante'
      fullPath: '/restaurante'
      preLoaderRoute: typeof RestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro-de-reclamaciones': {
      id: '/libro-de-reclamaciones'
      path: '/libro-de-reclamaciones'
      fullPath: '/libro-de-reclamaciones'
      preLoaderRoute: typeof LibroDeReclamacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia-las-flores': {
      id: '/familia-las-flores'
      path: '/familia-las-flores'
      fullPath: '/familia-las-flores'
      preLoaderRoute: typeof FamiliaLasFloresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta': {
      id: '/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof CartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreo/$orderId': {
      id: '/rastreo/$orderId'
      path: '/rastreo/$orderId'
      fullPath: '/rastreo/$orderId'
      preLoaderRoute: typeof RastreoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$orderId': {
      id: '/d/$orderId'
      path: '/d/$orderId'
      fullPath: '/d/$orderId'
      preLoaderRoute: typeof DOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CajaRoute: CajaRoute,
  CartaRoute: CartaRoute,
  ContactoRoute: ContactoRoute,
  EventosRoute: EventosRoute,
  FamiliaLasFloresRoute: FamiliaLasFloresRoute,
  GaleriaRoute: GaleriaRoute,
  LibroDeReclamacionesRoute: LibroDeReclamacionesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  ReservasRoute: ReservasRoute,
  RestauranteRoute: RestauranteRoute,
  StaffLoginRoute: StaffLoginRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  TesorosAyacuchoRoute: TesorosAyacuchoRoute,
  UneteAlEquipoRoute: UneteAlEquipoRoute,
  DOrderIdRoute: DOrderIdRoute,
  RastreoOrderIdRoute: RastreoOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
